### ISSUE TITLE
Doesn't seem to render in Gatsby and errors in CodeSandbox

### ISSUE THREAD

**Issue by spences10** [ConvertKit/convertkit-react#1]
Hi, thanks for this.

I tried this out this morning and it wouldn't render in my Gatsby project so I tried in a CodeSandbox and that gave a reference error "React is not defined"

I have imported the lib and used the example from the README, it seems that earlier versions work 0.0.1-0.0.3 but nothing more recent.

Reproduction here: https://codesandbox.io/s/strange-rubin-q8246?file=/src/App.js

Thanks

**Comment by josephrexme** [comment]
Hi @spences10 this should be fixed in version `1.0.6` that was just pushed. I'm sorry you had to deal with the inconvenience

**Comment by spences10** [comment]
Yay! Can confirm working in Gatsby, thanks 🙏

I close, now.
