### ISSUE TITLE
Console error in Next.js

### ISSUE THREAD

**Issue by dashbaz** [ConvertKit/convertkit-react#19]
Following the readme. This came up in console from the basic example. 

Is there anyone who could provide some help with this with steps to fix this?

Thanks! 

![Screen Shot 2022-05-09 at 9 17 34 PM](https://user-images.githubusercontent.com/90878373/167528170-f18e44ab-c389-4f63-9360-83b197e2fb86.png)

**Comment by nelakay** [comment]
I have this same issue. Is there a solution for this?
