### ISSUE TITLE
Missing templates & options

### ISSUE THREAD

**Issue by Emsu** [ConvertKit/convertkit-react#3]
I tried to setup using "poplar" and it's not working. It looks like all the newer designs are missing.

Also you can't edit the background image for template. It seems a lot of the options in the visual designer are missing.

**Comment by josephrexme** [comment]
This should be addressed soon.

**Comment by josephrexme** [comment]
You should be able to set custom background and opacity in [1.4.3](https://github.com/ConvertKit/convertkit-react/releases/tag/v1.4.3)

**Comment by josephrexme** [comment]
Templates are now updated and more options have been added in version [1.5.0](https://github.com/ConvertKit/convertkit-react/releases/tag/v1.5.0)
