### ISSUE TITLE
Support setting the button color

### ISSUE THREAD

**Issue by RobertBrunhage** [ConvertKit/convertkit-react#4]
Using the Clare template but I really need to set the color of the button, is it something you support / will support?

**Comment by josephrexme** [comment]
Yes. Planning on adding support for this soon @RobertBrunhage

**Comment by josephrexme** [comment]
This has now been added in [this commit](https://github.com/ConvertKit/convertkit-react/commit/db4378feaad0e55063b93616dd0d467a3cb11266)
