### ISSUE TITLE
Support setting the 'success message'

### ISSUE THREAD

**Issue by theandersonn** [ConvertKit/convertkit-react#6]
I'm using the cocoa model, it has support to change by prop for 'Show a success message'?

**Comment by josephrexme** [comment]
@theandersonn I'm hoping to be able to have your settings from the app loaded to CK React forms. This is why this isn't being addressed yet. For now this only allows to change settings related to the form's design

**Comment by theandersonn** [comment]
Ok, thank you for the feedback.
